accounts:
  - name: $10M (B/S=3.25/6.75)
    key_id: "PKFZQFQF5XNQDGAABGOZYAUQKS"
    secret_key: "67wPW5mc9pia9imijK2ZmmNyvyccKKumT2c2LaDSVQ8i"
    base_url: "https://paper-api.alpaca.markets"
    allocation_basis: equity  # or cash
    max_notional_per_order: 5000
    allocations:
      - symbol: VOO
        percentage: 0.26        # 10% of selected basis
        side: buy
        time_in_force: day
        allocation_basis: cash  # override per symbol
      - symbol: QQQ
        percentage: 0.18
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: VEA
        percentage: 0.125
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: VWO
        percentage: 0.110
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: VTEB
        percentage: 0.105
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: TIP
        percentage: 0.08
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: IEF
        percentage: 0.03
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: VNQ
        percentage: 0.04
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: SHYG
        percentage: 0.02
        side: buy
        allocation_basis: cash  # override per symbol
      - symbol: GLD
        percentage: 0.05
        side: buy
        allocation_basis: cash  # override per symbol

  - name: $10M (B/S=5.25/4.75)
    key_id: "PKP3UVHGZBDAPZBNTA2OTM3RA3"
    secret_key: "Dy9rqsDT4wVuaSSBURedwgUuKdSxzdL2REfHj5uhD2YM"
    base_url: "https://paper-api.alpaca.markets"
    allocation_basis: cash
    max_notional_per_order: 2500
    allocations:
      - symbol: VOO
        percentage: 0.19
        side: buy
        time_in_force: day
        allocation_basis: equity
        min_notional: 50
      - symbol: QQQ
        percentage: 0.13
        side: buy
        allocation_basis: equity
      - symbol: VEA
        percentage: 0.09
        side: buy
        allocation_basis: equity
      - symbol: VWO
        percentage: 0.065
        side: buy
        allocation_basis: equity
      - symbol: VTEB
        percentage: 0.185
        side: buy
        allocation_basis: equity
      - symbol: TIP
        percentage: 0.13
        side: buy
        allocation_basis: equity
      - symbol: IEF
        percentage: 0.06
        side: buy
        allocation_basis: equity
      - symbol: VNQ
        percentage: 0.03
        side: buy
        allocation_basis: equity
      - symbol: SHYG
        percentage: 0.05
        side: buy
        allocation_basis: equity
      - symbol: GLD
        percentage: 0.07
        side: buy
        allocation_basis: equity

  